spring.application.name=Book_My_Cini

# Database configuration Hana
spring.datasource.url=jdbc:sap://f06f0610-720e-483c-89bc-80bd276dddf8.hana.trial-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=DF09B3DC4E22431CA5544344C85CF92E
spring.datasource.username=DF09B3DC4E22431CA5544344C85CF92E_AN1EPLJL9Y3XUP1PWBB5KXVL8_RT
spring.datasource.password=Br2B1ccMvDYL.ndUWPZEr_IiKw3VE0GfQ3tJQ4jVy0.E4Yv67eOtbzORoP21F352iOTGT1L5HojkFH2l4OfhLzWLgeqnHOi6pyeg-p5DhAB0ndl-VGJxXgblCq2Jut0x
spring.datasource.driver-class-name=com.sap.db.jdbc.Driver

# Hibernate configuration Hana
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HANARowStoreDialect
