spring.profiles.active=local
spring.application.name=Book_My_Cini

# Optional: Configure logging level
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Security
spring.security.user.name=pream
spring.security.user.password=kumar
#security.enabled=false

# swagger
springdoc.swagger-ui.path=/custom-swagger-ui
